<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ECommerce.Shared" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Basket.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
  </ItemGroup>

</Project>
